### ISSUE TITLE
可否全自动化破解当前网络中的所有WiFi？

### ISSUE THREAD

**Issue by linksecho** [baihengaead/wifi-crack-tool#10]
即运行后扫描当前环境中的WiFi，然后自动化依次破解，破解成功的记录下密码，破解不成功的记录下破解失败，直到破解完当前环境中所有的WiFi为止。这样挂一晚上也就差不多了都。

**Comment by linksecho** [comment]
> 即运行后扫描当前环境中的WiFi，然后自动化依次破解，破解成功的记录下密码，破解不成功的记录下破解失败，直到破解完当前环境中所有的WiFi为止。这样挂一晚上周围的WiFi也就差不多了，现在是密码字典两千多条，每半小时还要手动跟换WiFi。

**Comment by baihengaead** [comment]
将在下个版本更新

**Comment by linksecho** [comment]
> 将在下一个版本更新

非常期待！

**Comment by baihengaead** [comment]
已在v1.2版本更新，可以尝试使用了，[使用方法](https://github.com/baihengaead/wifi-crack-tool?tab=readme-ov-file#%E8%87%AA%E5%8A%A8%E8%BF%90%E8%A1%8C)
