### ISSUE TITLE
扫描wifi时出错

### ISSUE THREAD

**Issue by yunzimo** [baihengaead/wifi-crack-tool#13]
![image](https://github.com/user-attachments/assets/148463b7-8cc3-4b43-9476-898b727622a1)

![image](https://github.com/user-attachments/assets/10c50a01-39f1-4b20-b8ba-0c977f54d28e)

笔记本Win11，使用内置网卡进行wifi扫描时报错，插上usb网卡打开软件提示另一个软件示例已经在运行

**Comment by baihengaead** [comment]
关于第二个问题“在多个网卡的情况下运行软件，提示 应用程序的另一个实例已经在运行 ”已定位到问题点。

第一个问题应该出在对WiFi名称(SSID)进行编码转换时，遇到特殊字符导致转换出错。

为了复现和修复第一个问题，方便提供一下当前系统的WiFi列表截图吗？

**Comment by yunzimo** [comment]
> 关于第二个问题“在多个网卡的情况下运行软件，提示 应用程序的另一个实例已经在运行 ”已定位到问题点。
> 
> 第一个问题应该出在对WiFi名称(SSID)进行编码转换时，遇到特殊字符导致转换出错。
> 
> 为了复现和修复第一个问题，方便提供一下当前系统的WiFi列表截图吗？

![image](https://github.com/user-attachments/assets/03c641bf-97cd-401f-8bf4-50b60ca113b3)

**Comment by baihengaead** [comment]
> > 关于第二个问题“在多个网卡的情况下运行软件，提示 应用程序的另一个实例已经在运行 ”已定位到问题点。
> > 
> > 第一个问题应该出在对WiFi名称(SSID)进行编码转换时，遇到特殊字符导致转换出错。
> > 
> > 为了复现和修复第一个问题，方便提供一下当前系统的WiFi列表截图吗？
> 
> ![image](https://github.com/user-attachments/assets/03c641bf-97cd-401f-8bf4-50b60ca113b3)
> 

感谢提供，问题将在下个版本中修复

**Comment by baihengaead** [comment]
已更新[1.2.2](https://github.com/baihengaead/wifi-crack-tool/releases/tag/v1.2.2)版本，试试看问题是否已解决？
[当前问题](https://github.com/baihengaead/wifi-crack-tool/issues/13)将保持开启状态，如问题已解决，可以关闭这个问题。

**Comment by yunzimo** [comment]
上述问题都已经解决，👏👏👏

**Comment by becausecx** [comment]
用了1.2.4还是出现了该情况![IMG_20241025_192018.jpg](https://github.com/user-attachments/assets/adac4b7e-8a37-4a3f-91a2-5cd19295bfbb)

**Comment by baihengaead** [comment]
> 用了1.2.4还是出现了该情况![IMG_20241025_192018.jpg](https://github.com/user-attachments/assets/adac4b7e-8a37-4a3f-91a2-5cd19295bfbb)
> 
> 

只有一个无线网卡的情况下不允许多开
