### ISSUE TITLE
密码本不存在

### ISSUE THREAD

**Issue by kissyou6661** [baihengaead/wifi-crack-tool#14]
默认密码本［passwords.ttj不存在！
请选择密码本

**Comment by baihengaead** [comment]
请在项目源码处下载[密码本](https://github.com/baihengaead/wifi-crack-tool/blob/main/passwords.txt)，或者自行创建密码本，[密码本格式](https://github.com/baihengaead/wifi-crack-tool/?tab=readme-ov-file#%E9%BB%98%E8%AE%A4%E5%AF%86%E7%A0%81%E6%9C%AC)
