### ISSUE TITLE
出现错误警告

### ISSUE THREAD

**Issue by jindutian** [baihengaead/wifi-crack-tool#18]
扫描WiFi点开始以后出现错误警告的弹窗，并提示“连接wifi过程中发生未知错误 'int' object has no attribute 'append'”

**Comment by baihengaead** [comment]
请按以下格式反馈

1. 操作系统：Windows？
2. 软件版本：1.2.3？
3. 发生错误前的操作过程描述：扫描WiFi点开始以后出现错误警告的弹窗？
4. 日志截图：
5. 是否为release版本：是？

**Comment by mishiqi9** [comment]
请问密码本在哪里下载
