### ISSUE TITLE
扫描wifi出现错误

### ISSUE THREAD

**Issue by sunhotblaze** [baihengaead/wifi-crack-tool#28]
2024-10-20 20:18:34 >> 已搜索到无线网卡（数量:1）
2024-10-20 20:18:34 >> 初始化完成！
2024-10-20 20:18:37 >> 正在使用网卡[Intel(R) Wi-Fi 6 AX201 160MHz]扫描WiFi...
2024-10-20 20:18:45 >> 扫描wifi时发生未知错误 NULL pointer access

2024-10-20 20:20:20 >> 正在使用网卡[Intel(R) Wi-Fi 6 AX201 160MHz]扫描WiFi...
2024-10-20 20:20:28 >> 扫描wifi时发生未知错误 NULL pointer access

2024-10-20 20:20:31 >> 正在使用网卡[Intel(R) Wi-Fi 6 AX201 160MHz]扫描WiFi...
2024-10-20 20:20:39 >> 扫描wifi时发生未知错误 NULL pointer access

2024-10-20 20:22:57 >> 正在使用网卡[Intel(R) Wi-Fi 6 AX201 160MHz]扫描WiFi...
2024-10-20 20:23:05 >> 扫描wifi时发生未知错误 NULL pointer access

**Comment by baihengaead** [comment]
> 2024-10-20 20:18:34 >> 已搜索到无线网卡（数量:1）
> 2024-10-20 20:18:34 >> 初始化完成！
> 2024-10-20 20:18:37 >> 正在使用网卡[Intel(R) Wi-Fi 6 AX201 160MHz]扫描WiFi...
> 2024-10-20 20:18:45 >> 扫描wifi时发生未知错误 NULL pointer access
> 
> 2024-10-20 20:20:20 >> 正在使用网卡[Intel(R) Wi-Fi 6 AX201 160MHz]扫描WiFi...
> 2024-10-20 20:20:28 >> 扫描wifi时发生未知错误 NULL pointer access
> 
> 2024-10-20 20:20:31 >> 正在使用网卡[Intel(R) Wi-Fi 6 AX201 160MHz]扫描WiFi...
> 2024-10-20 20:20:39 >> 扫描wifi时发生未知错误 NULL pointer access
> 
> 2024-10-20 20:22:57 >> 正在使用网卡[Intel(R) Wi-Fi 6 AX201 160MHz]扫描WiFi...
> 2024-10-20 20:23:05 >> 扫描wifi时发生未知错误 NULL pointer access
> 

请按以下格式反馈

1. 操作系统：Windows 10？
2. 软件版本：1.2.4？
3. 发生错误前的操作过程描述：
4. 日志截图：
5. 是否为release版本：是？

**Comment by sunhotblaze** [comment]
操作系统：Windows 11 LTSC
软件版本：1.2.4
发生错误前的操作过程描述：之前启动成功过，后面停止了然后就无法扫描WiFi了
日志截图：
是否为release版本：是

**Comment by baihengaead** [comment]
已更新，可以尝试一下[v1.2.5](https://github.com/baihengaead/wifi-crack-tool/releases/tag/v1.2.5)

**Comment by Liuxin4950** [comment]
<img width="429" alt="捕获" src="https://github.com/user-attachments/assets/02b3bc2b-7fee-48d5-aee6-c33bd4974ed0" />
同款错误

**Comment by Rich-Superman** [comment]
空指针异常

**Comment by 123xld** [comment]
> <img alt="捕获" width="429" src="https://private-user-images.githubusercontent.com/130823291/402356886-02b3bc2b-7fee-48d5-aee6-c33bd4974ed0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY5NTEyNjMsIm5iZiI6MTc0Njk1MDk2MywicGF0aCI6Ii8xMzA4MjMyOTEvNDAyMzU2ODg2LTAyYjNiYzJiLTdmZWUtNDhkNS1hZWU2LWMzM2JkNDk3NGVkMC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUxMVQwODA5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTllMmFkMjMyMTViNzZlMDY3ZjM3OGJjMGJmNTI0OTQ4NjcwNTQ5NTZlY2I4NTRkMjUxZmQ3Yjk4ZGNmZjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._hwLam79ejlOBbUKbnjYJw87Tp0XlhZxLzFLERCuG1s"> 同款错误

我也是同款错误

**Comment by 123xld** [comment]
![Image](https://github.com/user-attachments/assets/84a75990-1d33-4c36-b000-9e47400ab332)
操作系统：Windows 11 专业版
软件版本：1.2.5
发生错误前的操作过程描述：所有版本都未成功，都报相同的错误
日志截图：
是否为release版本：是
