### ISSUE TITLE
速度太慢了吧！（验证一个密码，要两秒），我丢

### ISSUE THREAD

**Issue by xk-mt** [baihengaead/wifi-crack-tool#4]
![image](https://github.com/baihengaead/wifi-crack-tool/assets/77874955/efabc0b5-9914-4a32-abf1-1a9301e04ec8)

**Comment by baihengaead** [comment]
验证一个是1秒，觉得慢的话可以自己改一下，在264行 `time.sleep(1)   #连接需要时间`

**Comment by xk-mt** [comment]
![image](https://github.com/baihengaead/wifi-crack-tool/assets/77874955/e8717e75-7763-4673-8a91-0d97f60374b6)
可以啊，嘎嘎快了但是爆破出真的可能太难了，但还是谢谢
