### ISSUE TITLE
有点慢，能不能多线程

### ISSUE THREAD

**Issue by tettst** [baihengaead/wifi-crack-tool#5]

**Comment by baihengaead** [comment]
单个无线网卡不支持，如果你有多个无线网卡 可以自行修改源码实现多线程

**Comment by fwdsc** [comment]
![image](https://github.com/baihengaead/wifi-crack-tool/assets/133293020/1e90df4a-f09d-4005-873a-d1c256f00ef9)

环境部署完成，pip更新到最新版遇到这个问题
