### ISSUE TITLE
破解不了wifi

### ISSUE THREAD

**Issue by skt12315** [baihengaead/wifi-crack-tool#9]
简单使用，一个网卡，密码本的密码都试过了，都没有破解。有没有破解成功的

**Comment by linksecho** [comment]
你换个密码本，然后先试试自己的WIFI弱密码看看

**Comment by baihengaead** [comment]
建议先对自己的WiFi进行破解，测试功能是否正常，功能正常的情况下，能否破解成功取决于你的密码本
